HEAD = bytes([126, 126])
STOP = bytes([10, 13])

BROADCAST_ADDR = 255

TYPE_OUTPUT_SWITCH = 1
TYPE_SIGNAL_CONTROL = 2
TYPE_STATUS_QUERY = 255
TYPE_ADDR_QUERY = 191
TYPE_ADDR_SET = 177

OUTPUT_OFF = 0
OUTPUT_ON = 1

MODE_WHITE_NOISE = 0
MODE_LINEAR_SWEEP = 1
MODE_COMB_SPECTRUM = 2
MODE_SINGLE = 3

MODE_NAMES = {
    MODE_WHITE_NOISE: "Pseudo Random Noise",
    MODE_LINEAR_SWEEP: "Linear Sweep",
    MODE_COMB_SPECTRUM: "Multi-tone",
    MODE_SINGLE: "Continuous Wave (CW)",
}

MODES_UNCONFIRMED = frozenset({MODE_SINGLE})

BANDWIDTH_CODES = {
    10: 0,
    20: 1,
    50: 2,
    100: 3,
    150: 4,
    200: 5,
    250: 6,
    300: 7,
}
BANDWIDTH_CODES_REV = {v: k for k, v in BANDWIDTH_CODES.items()}

BANDWIDTH_UNCONFIRMED = frozenset({300})

RESP_FAILED = 1
RESP_SUCCESS = 255

FREQ_MIN_MHZ = 300
FREQ_MAX_MHZ = 6000

ADDR_MIN = 0
ADDR_MAX = 199

BLIND_DEFAULT_MODE = MODE_WHITE_NOISE
BLIND_DEFAULT_FREQ_MHZ = 2450
BLIND_DEFAULT_BANDWIDTH_MHZ = 100
